# Generated by Django 2.0.3 on 2018-05-17 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price_design',
            name='cost',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='price_largeformatpress',
            name='category',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='price_largeformatpress',
            name='cost',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='price_offsetpress',
            name='price1000',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='price_offsetpress',
            name='price2000',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='price_offsetpress',
            name='price5000',
            field=models.CharField(max_length=5),
        ),
    ]
