# Generated by Django 2.0.3 on 2018-05-20 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0002_auto_20180517_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price_offsetpress',
            name='price1000',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='price_offsetpress',
            name='price2000',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='price_offsetpress',
            name='price5000',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
