# Generated by Django 2.0.3 on 2018-05-28 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0003_auto_20180521_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price_design',
            name='cost',
            field=models.CharField(max_length=5, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='price_design',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название услуги'),
        ),
        migrations.AlterField(
            model_name='price_largeformatpress',
            name='category',
            field=models.CharField(max_length=200, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='price_largeformatpress',
            name='cost',
            field=models.CharField(max_length=5, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='price_largeformatpress',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название продукции'),
        ),
        migrations.AlterField(
            model_name='price_offsetpress',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название продукции'),
        ),
        migrations.AlterField(
            model_name='price_offsetpress',
            name='price1000',
            field=models.CharField(blank=True, max_length=5, verbose_name='1000шт'),
        ),
        migrations.AlterField(
            model_name='price_offsetpress',
            name='price2000',
            field=models.CharField(blank=True, max_length=5, verbose_name='2000шт'),
        ),
        migrations.AlterField(
            model_name='price_offsetpress',
            name='price5000',
            field=models.CharField(blank=True, max_length=5, verbose_name='5000шт'),
        ),
    ]
