# Generated by Django 2.0.3 on 2018-05-28 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0004_auto_20180528_2333'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price_design',
            options={'verbose_name': 'Цены за дизайн', 'verbose_name_plural': 'Цены за дизайн'},
        ),
        migrations.AlterModelOptions(
            name='price_largeformatpress',
            options={'verbose_name': 'Цены по широкоформатной печати', 'verbose_name_plural': 'Цены по широкоформатной печати'},
        ),
        migrations.AlterModelOptions(
            name='price_offsetpress',
            options={'verbose_name': 'Цены по офсетной печати', 'verbose_name_plural': 'Цены по офсетной печати'},
        ),
    ]
