# Generated by Django 2.0.3 on 2018-05-16 21:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about_us',
            name='edit_date',
        ),
        migrations.AlterField(
            model_name='about_us',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
