# Generated by Django 2.0.3 on 2018-05-28 20:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0002_auto_20180517_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_us',
            name='text',
            field=ckeditor.fields.RichTextField(verbose_name='Текст о нас'),
        ),
    ]
