# Generated by Django 2.0.3 on 2018-05-28 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0003_auto_20180528_2333'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about_us',
            options={'verbose_name': 'Описание страницы "О НАС"', 'verbose_name_plural': 'Описание страницы "О НАС"'},
        ),
    ]
