# Generated by Django 2.0.3 on 2018-05-28 20:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20180521_0149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preview',
            name='image',
        ),
        migrations.AddField(
            model_name='preview',
            name='full_size',
            field=models.ImageField(default=django.utils.timezone.now, unique=True, upload_to='portfolio/static/img/full_size/', verbose_name='Оригинал'),
        ),
        migrations.AddField(
            model_name='preview',
            name='thumbs',
            field=models.ImageField(default=django.utils.timezone.now, unique=True, upload_to='portfolio/static/img/thumbs/', verbose_name='Превью'),
        ),
        migrations.AlterField(
            model_name='preview',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.Project', verbose_name='Принадлежность к проекту'),
        ),
        migrations.AlterField(
            model_name='preview',
            name='tag',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='portfolio.Tag', verbose_name='Тег изображения'),
        ),
        migrations.AlterField(
            model_name='preview',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок изображения'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок проекта'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_title',
            field=models.CharField(max_length=200, verbose_name='Тег'),
        ),
    ]
