# Generated by Django 2.0.3 on 2018-05-28 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20180528_2341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preview',
            options={'verbose_name': 'Превью проектов', 'verbose_name_plural': 'Превью проектов'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Проекты', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Теги', 'verbose_name_plural': 'Теги'},
        ),
    ]
