# Generated by Django 2.1.5 on 2019-02-11 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_auto_20190212_0043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preview',
            name='thumbs',
        ),
    ]
