# Generated by Django 2.1.5 on 2019-02-12 11:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_remove_preview_thumbs'),
    ]

    operations = [
        migrations.AddField(
            model_name='preview',
            name='thumbs',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='portfolio/thumbs/', verbose_name='Превью 200х200px'),
        ),
        migrations.AlterField(
            model_name='preview',
            name='full_size',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='portfolio/full_size/', verbose_name='Оригинал'),
        ),
    ]
