# Generated by Django 2.0.3 on 2018-05-28 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_auto_20180528_2333'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infopages',
            options={'verbose_name': 'Описание информационных страниц', 'verbose_name_plural': 'Описание информационных страниц'},
        ),
    ]
